version: "3.8"
services:
  api:
    build: ./api
    container_name: api_sk
    ports:
      - '5000:5000'
    volumes:
      - ./api:/app
      - /app/node_modules
  myblog:
    build: ./myblog
    container_name: myblog_sk
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true